# Generated by Django 4.0.5 on 2023-10-10 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mybookwishlist', '0004_rename_when_it_put_mybookwishlist_input_context_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybookwishlist',
            name='DELETED',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MybookWishlistGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('DELETED', models.BooleanField(default=False)),
                ('name', models.CharField(default='분류없음', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
    ]
