# Generated by Django 4.0.5 on 2023-10-10 08:24

from django.db import migrations, models
import django.db.models.deletion

from accounts.models import User


def make_default_group(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Mybookwishlist = apps.get_model("mybookwishlist", "Mybookwishlist")
    MybookwishlistGroup = apps.get_model("mybookwishlist", "MybookWishlistGroup")

    MybookwishlistGroup_obj = []
    for user in User.objects.all():
        MybookwishlistGroup_obj.append(MybookwishlistGroup(user=user, name="분류없음"))
    MybookwishlistGroup.objects.bulk_create(MybookwishlistGroup_obj)


class Migration(migrations.Migration):
    dependencies = [
        ("mybookwishlist", "0005_alter_mybookwishlist_deleted_mybookwishlistgroup"),
    ]

    operations = [
        migrations.RunPython(make_default_group),
    ]
