# Generated by Django 4.0.5 on 2023-09-11 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('DELETED', models.BooleanField(null=True)),
                ('lib_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.library')),
                ('small_region_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.smallregion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
