# Generated by Django 4.0.5 on 2023-09-28 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('barcode', '0001_initial'), ('barcode', '0002_remove_barcode_lib_code_barcode_isbn_and_more'), ('barcode', '0003_rename_isbn_barcode_isbn13'), ('barcode', '0004_barcode_user'), ('barcode', '0005_alter_barcode_user'), ('barcode', '0006_remove_barcode_user_barcode_username'), ('barcode', '0007_remove_barcode_username_barcode_user'), ('barcode', '0008_barcode_client')]

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('DELETED', models.BooleanField(null=True)),
                ('small_region_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.smallregion')),
                ('isbn13', models.CharField(default=1, max_length=13)),
                ('statusCode', models.CharField(default=1, max_length=1)),
                ('statusMsg', models.TextField(blank=True)),
                ('user', models.BigIntegerField(blank=True, null=True)),
                ('client', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
