# Generated by Django 4.2.5 on 2023-09-27 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0002_remove_barcode_lib_code_barcode_isbn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barcode',
            old_name='ISBN',
            new_name='isbn13',
        ),
    ]
