# Generated by Django 4.0.5 on 2023-09-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0002_alter_barcode_isbn13_alter_barcode_statuscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='ipaddress',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
    ]
