# Generated by Django 4.2.5 on 2023-09-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0006_remove_barcode_user_barcode_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcode',
            name='username',
        ),
        migrations.AddField(
            model_name='barcode',
            name='user',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
