# Generated by Django 4.0.5 on 2023-09-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0007_remove_barcode_username_barcode_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='client',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
