# Generated by Django 4.0.5 on 2023-10-10 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0009_alter_bigregion_deleted_alter_library_deleted_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='my_library',
            field=models.ForeignKey(blank=True, default=None, help_text='선호하는 도서관', null=True, on_delete=django.db.models.deletion.CASCADE, to='library.library'),
        ),
        migrations.AddField(
            model_name='user',
            name='my_region',
            field=models.ForeignKey(blank=True, default=None, help_text='바코드 검색시 기본으로 사용할 지역', null=True, on_delete=django.db.models.deletion.CASCADE, to='library.smallregion'),
        ),
    ]
