# Generated by Django 4.0.5 on 2023-09-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('DELETED', models.BooleanField(null=True)),
                ('isbn13', models.CharField(db_index=True, max_length=13, primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=10)),
                ('bookname', models.CharField(max_length=300)),
                ('publication_date', models.CharField(max_length=20)),
                ('authors', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('class_no', models.CharField(max_length=100)),
                ('class_nm', models.CharField(max_length=100)),
                ('bookImageURL', models.URLField()),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
