# Generated by Django 4.0.5 on 2023-10-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_bookimageurl_alter_book_class_nm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='DELETED',
            field=models.BooleanField(default=False),
        ),
    ]
